"use client";
import {useMemo,useState} from "react";
import ImageStoryFrame,{useStoryData} from "./ImageStoryFrame";
import {buildJourney,type JourneyItem} from "./scene-model";
import CostExplorer from "./CostExplorer";
import CostNodePanel from "./CostNodePanel";
import {CalculationPanel,formatCents} from "./IngredientPanels";
import type {PopupDetail} from "./JourneyPopup";
import "./cost-story-sections.css";
import "./cost-comparison-tabs.css";
const sections=[{id:"cost-overview",label:"Overview"},{id:"cost-layers",label:"Explore cost layers"},{id:"cost-details",label:"Inputs & calculation"},{id:"cost-retail",label:"Compare to retail"}];
const stories=[{id:"cost-layers",view:"layers",title:"Choose a layer. See its contribution.",description:"Ingredients, packaging, manufacturing, storage and freight are counted once in the physical-cost estimate."},{id:"cost-details",view:"detail",title:"Open the assumptions. Follow the arithmetic.",description:"Read the quantities, benchmark prices and allocation logic from the saved model."},{id:"cost-retail",view:"comparison",title:"Compare the estimate with the shelf.",description:"The commercial gap is not profit. Retail observations and modeled physical costs are separate measures."}] as const;
export default function CostStoryPage(){const{data,error}=useStoryData();const[scenario,setScenario]=useState<"low"|"base"|"high">("base"),[layer,setLayer]=useState("ingredient"),[detail,setDetail]=useState<PopupDetail|null>(null);const chapter=useMemo(()=>{const original=buildJourney(data,"cost",scenario)[0],center=original.items.find(item=>item.core);if(!data||!center)return original;const key=`${scenario}_cents_per_bar` as const;const ingredients:JourneyItem={id:"COST_GROUP_INGREDIENTS",label:"Ingredients",kind:"cost",color:"#d7b47f",artwork:"cocoa",tag:formatCents((data.costBreakdown.records||[]).filter(record=>record.safe_display&&record.cost_type==="ingredient").reduce((sum,record)=>sum+record[key],0))+" "+scenario};return{...original,items:[center,ingredients,...original.items.filter(item=>!item.core)],edges:[...original.edges,{id:"COSTREF:INGREDIENTS",source:ingredients.id,target:center.id,presentation:true,flowType:"cost_reference",relationshipStatus:"benchmark_only",tooltipText:"The sum of the ingredient records in this scenario, counted once in the physical cost estimate."}]};},[data,scenario]);
 const select=(item:JourneyItem)=>{if(!data)return;if(item.id==="COST_GROUP_INGREDIENTS"){setLayer("ingredient");setDetail({title:"Ingredient costs",content:<CostNodePanel key={item.id} data={data} ingredientsOnly initialScenario={scenario}/>});return;}if(item.core){setDetail({title:"Five layers, one physical-cost estimate",content:<CostNodePanel key={item.id} data={data} initialScenario={scenario}/>});return;}const record=data.costBreakdown.records?.find(record=>record.cost_bucket_id===item.id);if(record)setDetail({title:record.label,content:<CostNodePanel key={item.id} data={data} bucketId={record.cost_bucket_id} initialScenario={scenario}/>})};
 return <ImageStoryFrame route="/cost-model" world="cost" background="/home-art/cost-universe-reference.png" title={["What goes","into the price?"]} eyebrow="FROM BEAN TO BAR TO SHELF" intro="Explore the estimated cost to make and move one bar, then compare it with the shelf prices recorded in the research." sections={sections} chapter={chapter} detail={detail} onClose={()=>setDetail(null)} onSelect={select} error={error} heroControls={<div className="cost-scenario-picks" role="group" aria-label="Cost scenario">{(["low","base","high"] as const).map(value=><button key={value} aria-pressed={scenario===value} onClick={()=>setScenario(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>}>{data&&stories.map((story,index)=><section className="ih-story-card cost-full-section" data-home-section key={story.id} id={story.id}><div className="ih-card-heading"><span>{String(index+1).padStart(2,"0")} / {sections[index+1].label.toUpperCase()}</span><h2>{story.title}</h2><p>{story.description}</p></div><CostExplorer data={data} scenario={scenario} setScenario={setScenario} view={story.view} selectedLayer={layer} onLayerChange={setLayer}/></section>)}</ImageStoryFrame>;
}
