"use client";
import StoryQuestions from "./StoryQuestions";
import {useState} from "react";
import type {EnrichedArtifacts} from "@/lib/hershey/enrichedArtifacts";
import {CalculationPanel,formatCents,ingredientFamilies} from "./IngredientPanels";
import StoryObject,{type StoryObjectName} from "./StoryObject";
import NodeResearch from "./NodeResearch";
import "./panel-research.css";
import "./panel-fit.css";
type Scenario="low"|"base"|"high";
export default function CostNodePanel({data,bucketId,ingredientsOnly=false,initialScenario="base"}:{data:EnrichedArtifacts;bucketId?:string;ingredientsOnly?:boolean;initialScenario?:Scenario}){
 const[tab,setTab]=useState("overview"),[scenario,setScenario]=useState<Scenario>(initialScenario),[chosenId,setChosenId]=useState(bucketId||"");
 const all=(data.costBreakdown.records||[]).filter(record=>record.safe_display),rows=bucketId?all.filter(record=>record.cost_bucket_id===bucketId):all.filter(record=>ingredientsOnly?record.cost_type==="ingredient":!["retail_price","residual_channel_pool"].includes(record.cost_type));
 const chosen=rows.find(record=>record.cost_bucket_id===chosenId)||rows[0],key=`${scenario}_cents_per_bar` as const,total=rows.reduce((sum,record)=>sum+record[key],0);
 const object:StoryObjectName=ingredientsOnly?"cocoa":chosen?.cost_type==="packaging"?"packaging":chosen?.cost_type==="manufacturing_conversion"?"factory":chosen?.cost_type==="storage"?"warehouse":chosen?.cost_type==="freight"?"truck":"coins";
 const grouping=(record:typeof rows[number])=>!ingredientsOnly&&!bucketId?record.cost_type:record.family||record.cost_type;
 const families=Array.from(new Set(rows.map(grouping)));
 const researchRows=chosenId&&chosen?[chosen]:rows;
 const evidenceIds=Array.from(new Set(researchRows.flatMap(record=>record.current_context_reference_ids||[]))).filter(id=>data.evidence[id]?.public_display_allowed);
 const researchNode=({COST_PACKAGING_PRIMARY_SECONDARY:"NODE_COST_PACKAGING",COST_MANUFACTURING_CONVERSION:"NODE_COST_MANUFACTURING",COST_STORAGE_WAREHOUSING:"NODE_COST_STORAGE",COST_OUTBOUND_FREIGHT:"NODE_COST_FREIGHT"} as Record<string,string>)[chosenId||bucketId||""]||(ingredientsOnly?"NODE_COST_INGREDIENTS":"NODE_PRODUCT_HERSHEY_155OZ");
 return <div className="cost-node-panel" data-panel-view={tab} data-group-mode={ingredientsOnly?"ingredients":bucketId?"single":"whole"}><div className="panel-subject-lead"><div className="panel-subject-art"><StoryObject name={object}/></div><div><p className="ih-eyebrow">{ingredientsOnly?"INGREDIENT CONTRIBUTION":bucketId?"COST CONTRIBUTION":"MAKE AND MOVE ONE BAR"}</p><strong className="panel-primary-value">{formatCents(total)}</strong><p>{scenario[0].toUpperCase()+scenario.slice(1)} estimate per bar · {rows.length} {rows.length===1?"allocation":"cost records"}</p></div></div>
 <div className="cost-scenario-picks" role="group" aria-label="Panel cost scenario">{(["low","base","high"] as const).map(value=><button key={value} aria-pressed={scenario===value} onClick={()=>setScenario(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>
 <StoryQuestions label="Cost panel views" value={tab} onChange={setTab} items={[
{id:"overview",label:"Contributions",question:"What goes into this estimate?",hint:"Explore what is counted",art:object},
{id:"calculation",label:"Calculation",question:"How is this amount calculated?",hint:"Follow quantity and benchmark price",art:"charts"},
{id:"assumptions",label:"Assumptions",question:"What changes the estimate?",hint:"Understand the range and its limits",art:"audit"},
{id:"sources",label:"Reports",question:"What research sits behind it?",hint:"Read the originals in this panel",art:"report"}]}/>
 {tab==="overview"?<><p>{ingredientsOnly?"Sugar, cocoa ingredients, dairy and smaller inputs each contribute to this estimate. Select a group below to inspect the individual quantities and benchmark prices.":bucketId?chosen?.cost_logic:"Five contributions, counted once per bar—not the retail price."}</p><div className="panel-contribution-list">{families.map(family=>{const members=rows.filter(record=>grouping(record)===family),value=members.reduce((sum,record)=>sum+record[key],0),label=({ingredient:"Ingredients",manufacturing_conversion:"Manufacturing",storage:"Warehousing",freight:"Freight"} as Record<string,string>)[family]||ingredientFamilies[family as keyof typeof ingredientFamilies]?.label||members[0]?.label;return <button key={family} onClick={()=>{setChosenId(members[0].cost_bucket_id);setTab("calculation")}}><span><strong>{label}</strong><small>{!ingredientsOnly&&!bucketId?`${members.length} cost ${members.length===1?"record":"records"}`:members.map(record=>record.label).join(" · ")}</small></span><b>{formatCents(value)}</b><span aria-hidden="true">→</span></button>})}</div><p className="ih-fine">Modeled estimates, not company invoices. Shared allocations are counted once.</p></>:(tab==="calculation"||tab==="assumptions")?<><label className="panel-record-choice">Choose a cost record<select value={chosen?.cost_bucket_id||""} onChange={event=>setChosenId(event.target.value)}>{rows.map(record=><option key={record.cost_bucket_id} value={record.cost_bucket_id}>{record.label}</option>)}</select></label>{chosen&&(tab==="calculation"?<CalculationPanel record={chosen} scenario={scenario} data={data}/>:<section><h3>What the estimate assumes</h3><p>{chosen.cost_logic}</p><p>{chosen.notes}</p><dl className="story-facts"><div><dt>Published range per bar</dt><dd>{formatCents(chosen.low_cents_per_bar)}–{formatCents(chosen.high_cents_per_bar)}</dd></div><div><dt>Estimate confidence</dt><dd>{chosen.confidence_level?.replaceAll("_"," ")||"Not recorded"}</dd></div></dl></section>)}</> :<>{evidenceIds.length===0&&<p className="ih-fine">This allocation is a recorded model assumption. Related reports explain the context; they are not an invoice or proof of the exact amount.</p>}<NodeResearch key={researchNode+":"+chosenId} data={data} nodeId={researchNode} evidenceIds={evidenceIds.length?evidenceIds:undefined}/></>}
 </div>;
}
