"use client";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {ArrowRight,BookOpen,Search,Pause,Play,ShieldCheck} from "lucide-react";
import {loadEnrichedArtifacts,type EnrichedArtifacts,type EvidenceLookup} from "@/lib/hershey/enrichedArtifacts";
import ProjectHeader from "./ProjectHeader";
import ReferenceUniverse from "./ApprovedHomeUniverse";
import LivingFlowScene from "./LivingFlowScene";
import {buildJourney,type JourneyItem} from "./scene-model";
import {useSceneSession} from "./SceneSession";
import JourneyPopup,{type PopupDetail} from "./JourneyPopup";
import {EvidenceRecordDetail,documentTitle,scopeExplanation} from "./EvidenceExplorer";
import {HersheyOrb} from "./HersheyOrb";
import HomeSubjectArtwork from "./HomeSubjectArtwork";
import SiteFooter from "./SiteFooter";
import ResearchDocumentReader from "./ResearchDocumentReader";
import HomeEvidenceStories from "./HomeEvidenceStories";
import "./home-experience.css";
import "./section-journey.css";
import "./approved-home.css";
import "./image-led-home.css";
import "./evidence-led-page.css";
const sections=[{id:"evidence-overview",label:"Overview"},{id:"evidence-subjects",label:"Choose a subject"},{id:"evidence-record",label:"Inspect a record"},{id:"evidence-source",label:"Read the source"}];
const topics=[{id:"cocoa_chocolate_cocoa_butter",name:"Cocoa & chocolate",cell:0,color:"#e2bc90"},{id:"sugar",name:"Sugar",cell:1,color:"#eddaa4"},{id:"dairy_milk_skim_milk_milk_fat",name:"Milk & dairy",cell:2,color:"#a8e0f4"},{id:"product_sku_1_55oz",name:"Product label",cell:6,color:"#a8c6ef"},{id:"retail_price_evidence",name:"Retail prices",cell:7,color:"#e7c17c"}] as const;
export default function EvidencePage(){
 const[data,setData]=useState<EnrichedArtifacts|null>(null),[error,setError]=useState(""),[retry,setRetry]=useState(0),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),[active,setActive]=useState(0),[phase,setPhase]=useState(0),[detail,setDetail]=useState<PopupDetail|null>(null),[packet,setPacket]=useState("cocoa_chocolate_cocoa_butter"),[query,setQuery]=useState(""),[strength,setStrength]=useState(""),[selectedId,setSelectedId]=useState<string|null>(null),[page,setPage]=useState(0),[excerpt,setExcerpt]=useState(0);
 const focus=useSceneSession();
 useEffect(()=>{let on=true;setError("");loadEnrichedArtifacts().then(d=>{if(on){setData(d);setSelectedId(Object.values(d.evidence).find(e=>e.public_display_allowed&&e.packet==="cocoa_chocolate_cocoa_butter")?.evidence_id||null)}}).catch(e=>{if(on)setError(String(e))});return()=>{on=false}},[retry]);
 useEffect(()=>{const m=matchMedia("(prefers-reduced-motion: reduce)"),sync=()=>setReduced(m.matches);sync();m.addEventListener("change",sync);return()=>m.removeEventListener("change",sync)},[]);
 useEffect(()=>{const update=()=>{if(detail)return;let current=0,p=0;document.querySelectorAll<HTMLElement>(".evidence-led-page [data-home-section]").forEach((el,i)=>{const r=el.getBoundingClientRect();if(r.top<=innerHeight*.35){current=i;p=i+Math.max(0,Math.min(.99,(innerHeight*.35-r.top)/r.height))}});setActive(current);setPhase(p)};update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update)},[data,detail]);
 const chapters=useMemo(()=>[buildJourney(data,"evidence")[0]],[data]);
 const records=useMemo(()=>Object.values(data?.evidence||{}).filter(e=>e.public_display_allowed),[data]);
 const results=useMemo(()=>records.filter(e=>(!packet||e.packet===packet)&&(!strength||e.confidence_level===strength)&&[e.file_name,e.evidence_text,e.evidence_text_preview,e.audited_safe_website_wording].join(" ").toLowerCase().includes(query.toLowerCase())),[records,packet,strength,query]);
 const selected=(selectedId?data?.evidence[selectedId]:null)||results[0];
 const sourceText=selected?.evidence_text||selected?.evidence_text_preview||"No captured text is available for this record.";
 const choose=(entry:EvidenceLookup[string])=>{setSelectedId(entry.evidence_id||null);setExcerpt(0)};
 const chooseTopic=(id:string)=>{setPacket(id);setPage(0);const first=records.find(e=>e.packet===id);if(first)choose(first)};
 const inspect=(item:JourneyItem)=>{if(!data)return;if(item.core){setDetail({title:"Explore the research behind the model",content:<HomeEvidenceStories data={data}/>});return;}const e=item.kind==="evidence"?data.evidence[item.id]:item.kind==="source"?records.find(record=>record.file_name===item.id.slice(4)):selected;if(e)setDetail({title:documentTitle(e.file_name),content:<EvidenceRecordDetail key={e.evidence_id} entry={e}/>})};
 return <div id="top" className="hc-home image-led-home evidence-led-page" data-active-section={active} data-motion-paused={paused||reduced}><ReferenceUniverse artPath="/home-art/evidence-universe-reference.png" worldName="evidence" progress={phase} paused={paused||reduced}/><a href="#evidence-main" className="hc-skip">Skip to content</a><ProjectHeader current="/evidence-brain"/>{!detail&&<nav className="ih-section-rail" aria-label="Evidence sections">{sections.map((s,i)=><a href={"#"+s.id} key={s.id} aria-current={active===i?"step":undefined}><span>{String(i).padStart(2,"0")}</span><b>{s.label}</b><i aria-hidden="true"/></a>)}</nav>}
 <main id="evidence-main"><section className="ih-hero" data-home-section id="evidence-overview"><div className="ih-hero-copy"><p className="ih-eyebrow">FROM A QUESTION TO ITS SOURCE</p><h1>Follow a claim<span>to its source.</span></h1><p className="ih-intro">Explore ingredient research, company context and retailer observations. Read what each record supports—and what remains uncertain.</p><a className="ih-primary" href="#evidence-subjects">Find the research <ArrowRight size={21}/></a>{error&&<div role="alert"><p>Research could not load.</p><button onClick={()=>setRetry(retry+1)}>Try again</button></div>}</div><div className="ih-scene" data-retained={Boolean(detail&&focus.session?.mode==="scene")} data-panel-side={focus.session?.side||"right"}><LivingFlowScene chapters={chapters} progress={0} connectionStyle="constellation" paused={paused||reduced} visible={active===0} interactive={Boolean(data)} onSelect={inspect}/></div></section>
 <div className="ih-stories">{data&&<><section className="ih-story-card" data-home-section id="evidence-subjects"><div className="ih-card-heading"><span>01 / FILTER BY SUBJECT</span><h2>Choose your question.<br/>Narrow the research.</h2><p>Select a subject, search a document or compare the study's evidence-strength assessments.</p></div><div className="el-subject-scene"><div className="el-subject-picks" role="group" aria-label="Evidence subjects">{topics.map(t=><button key={t.id} aria-pressed={packet===t.id} onClick={()=>chooseTopic(t.id)} style={{"--subject-color":t.color} as CSSProperties}><HersheyOrb color={t.color} size={77} decorative><HomeSubjectArtwork cell={t.cell}/></HersheyOrb><span>{t.name}</span></button>)}</div><label className="el-search"><Search size={20}/><input aria-label="Search research" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Search claims, companies or documents…"/></label><div className="el-filters"><label>Subject<select aria-label="Research subject" value={packet} onChange={e=>{chooseTopic(e.target.value);setPage(0)}}><option value="">All subjects</option>{data.packetSummary.map(p=><option key={p.packet} value={p.packet}>{p.display_name?.replace(/ Evidence$/i,"")}</option>)}</select></label><label>Evidence strength<select value={strength} onChange={e=>{setStrength(e.target.value);setPage(0)}}><option value="">All levels</option>{Array.from(new Set(records.map(e=>e.confidence_level).filter(Boolean))).map(value=><option key={value} value={value}>{value?.replaceAll("_"," ")}</option>)}</select></label></div></div><div className="ih-inline-detail el-results"><h3>Research to explore</h3><p role="status">{results.length} matching records</p>{results.slice(page*3,page*3+3).map(e=><button key={e.evidence_id} aria-pressed={selected?.evidence_id===e.evidence_id} onClick={()=>choose(e)}><BookOpen size={22}/><span><strong>{documentTitle(e.file_name)}</strong><small>{e.confidence_level?.replaceAll("_"," ")} evidence strength</small></span></button>)}{!results.length&&<p>No records match. Try another phrase or choose All subjects.</p>}<div className="el-pagination"><button disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>{results.length?page+1:0} / {Math.ceil(results.length/3)}</span><button disabled={(page+1)*3>=results.length} onClick={()=>setPage(page+1)}>Next</button></div>{selected&&<a className="ih-inline-action" href="#evidence-record">Inspect the selected record <ArrowRight size={17}/></a>}</div></section>
 <section className="ih-story-card" data-home-section id="evidence-record"><div className="ih-card-heading"><span>02 / INSPECT THE RECORD</span><h2>Read its meaning.<br/>Keep the limits visible.</h2><p>Product evidence, company-level context and price observations are not interchangeable.</p></div><div className="el-document-scene"><HersheyOrb size={115} color="#a9dff6" decorative><HomeSubjectArtwork cell={6}/></HersheyOrb><h3>{documentTitle(selected?.file_name)}</h3><p>{scopeExplanation(selected?.safe_scope)}</p><a className="ih-inline-action" href="#evidence-source">Continue to the source <ArrowRight size={17}/></a></div><div className="ih-inline-detail el-record-detail">{selected?<EvidenceRecordDetail key={selected.evidence_id} entry={selected}/>:<p>Select a research record above.</p>}</div></section>
 <section className="ih-story-card" data-home-section id="evidence-source"><div className="ih-card-heading"><span>03 / READ THE SOURCE</span><h2>From interpretation<br/>back to the document.</h2><p>Read the original report in context, with its own pages, charts and tables.</p></div><div className="el-document-scene"><HersheyOrb size={100} color="#b9c5f3" decorative><HomeSubjectArtwork cell={6}/></HersheyOrb><h3>{documentTitle(selected?.file_name)}</h3><p className="el-source-limit"><ShieldCheck size={20}/>The source document and the study’s interpretation remain separate. A report is not proof of the exact journey taken by this bar.</p></div><div className="ih-inline-detail el-reader"><ResearchDocumentReader fileName={selected?.file_name} text={sourceText}/></div></section></>}</div></main><SiteFooter/><button className="ih-motion" disabled={reduced} aria-pressed={paused||reduced} onClick={()=>setPaused(!paused)}>{paused||reduced?<Play size={14}/>:<Pause size={14}/>} {reduced?"Reduced motion":paused?"Resume motion":"Pause motion"}</button><JourneyPopup detail={detail} onClose={()=>setDetail(null)}/></div>;
}
