"use client";
import {documentIdentity} from "@/lib/hershey/documentIdentity";
import {useState} from "react";
import type {EnrichedArtifacts} from "@/lib/hershey/enrichedArtifacts";
import StoryObject,{type StoryObjectName} from "./StoryObject";
import NodeResearch from "./NodeResearch";
import "./panel-research.css";
const objects:StoryObjectName[]=["archive","scanner","database","audit","packets","graph","charts","website"];
const inputs=["Original reports, policies, product pages and retailer observations","Collected source documents","Extracted text, table and image-text passages","Source-attributed evidence records","Records qualified for their intended use","Structured ingredient, company, process and cost subjects","The qualified graph, evidence and cost records","Published display data and original-document assets"];
const outputs=["A source collection with document identities","Searchable passages that retain their document context","Individually attributed evidence records","Recorded scope, evidence strength and public-display decisions","Linked ingredient, supplier, cost and logistics context","A navigable set of subjects and relationships","Data that the interface can present without inventing claims","An interactive explanation with a route back to the research"];
export default function MethodStageDetail({data,index,title,body}:{data:EnrichedArtifacts;index:number;title:string;body:string}){
 const[tab,setTab]=useState("role");const records=Object.values(data.evidence).filter(record=>record.public_display_allowed),files=new Set(records.map(record=>documentIdentity(record.file_name||"")));
 const facts=index===0?[["Documents in the public reading collection",files.size]]:index===1?[["Text/table records available for display",records.filter(record=>record.source_type==="text_or_table").length],["OCR-derived records available for display",records.filter(record=>record.source_type==="visual_ocr").length]]:index===2?[["Evidence lookup entries",Object.keys(data.evidence).length],["Public-display entries",records.length]]:index===3?Object.entries(data.manifest.audit_summary?.audit_status_counts||{}).map(([name,count])=>[name.replaceAll("_"," "),count]):index===4?[["Research subject groups",data.packetSummary.length],["Ingredient cards",data.ingredients.length],["Company-context cards",data.suppliers.length],["Cost records",data.costBreakdown.records?.length||0]]:index===5?[["Graph subjects",data.graph.nodes.length],["Recorded connections",data.graph.edges.length],["Subjects with assigned evidence",data.panelResearch.coverage.nodes_with_graph_assigned_evidence],["Subjects without direct assignments",data.panelResearch.coverage.nodes_without_direct_evidence.length]]:index===6?[["Display artifact groups",Object.keys(data.manifest.primary_artifacts).length],["Public-display records",records.length]]:[["Website pages",6],["Original source documents",files.size]];
 return <div className="method-stage-detail"><div className="panel-context-lead"><div className="panel-subject-art"><StoryObject name={objects[index]}/></div><div><p className="ih-eyebrow">STAGE {index+1} OF 8</p><h3>{title}</h3></div></div><div className="ih-detail-tabs" role="group" aria-label="Workflow stage detail"><button aria-pressed={tab==="role"} onClick={()=>setTab("role")}>What happens</button><button aria-pressed={tab==="data"} onClick={()=>setTab("data")}>Recorded data</button><button aria-pressed={tab==="research"} onClick={()=>setTab("research")}>Inspect the research</button></div>{tab==="role"?<><p>{body}</p><dl className="story-facts"><div><dt>What enters this stage</dt><dd>{inputs[index]}</dd></div><div><dt>What it produces</dt><dd>{outputs[index]}</dd></div></dl><p className="ih-fine">This describes the saved research workflow. Clicking a stage does not execute a new extraction, audit or AI job.</p></>:tab==="data"?<><p>Values below come from the published data snapshot, not a live processing counter.</p><dl className="story-facts">{facts.map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{index===5&&<p className="ih-fine">Related documents discovered by retrieval are kept separate from directly assigned evidence. Neither proves an exact shipment route.</p>}</>:<NodeResearch data={data} evidenceIds={records.map(record=>record.evidence_id!).filter(Boolean)}/>}</div>;
}
