"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import ImageStoryFrame,{useStoryData} from "./ImageStoryFrame";
import {buildJourney,type JourneyItem} from "./scene-model";
import {SubjectGlass} from "./StoryObject";
import HomeSubjectArtwork from "./HomeSubjectArtwork";
import {EvidenceRecordDetail,documentTitle} from "./EvidenceExplorer";
import ResearchDocumentReader from "./ResearchDocumentReader";
import type {PopupDetail} from "./JourneyPopup";
import MethodStageDetail from "./MethodStageDetail";
import ResponsibleStudyStory from "./ResponsibleStudyStory";
import "./evidence-led-page.css";
import "./method-mobile.css";
const sections=[{id:"method-overview",label:"Overview"},{id:"method-parse",label:"Parse sources"},{id:"method-audit",label:"Audit evidence"},{id:"method-result",label:"Responsible result"}];
const steps=[{title:"Source vault",body:"The project starts with collected company reports, ingredient information, distribution research and retailer observations. Each document keeps its identity."},{title:"Level 1 parser",body:"The parsing stage extracts text, tables and recognized image text. Extraction makes the material searchable; it does not establish that every sentence is accurate."},{title:"Evidence records",body:"Source passages become individually attributed records. The document name and supporting text remain attached so an interpretation can be checked."},{title:"Level 2 audit",body:"Records are assessed for their claim type, evidence strength and permitted scope. Company context is kept separate from exact product or supplier claims."},{title:"Structured packets",body:"Related records are organized into ingredient, supplier, logistics and cost packets. Shared subjects can then be connected without discarding their limits."},{title:"Node & edge builder",body:"The published graph connects named entities and modeled relationships. A visible link is not proof of a tracked shipment or an exact supplier allocation."},{title:"Display artifacts",body:"The frontend reads the published display records. Cost values, evidence status and relationship context are passed through rather than invented by the scene."},{title:"Interactive website",body:"The website lets readers explore a subject, inspect its calculation or supporting evidence, and return to the original document."}];
export default function MethodStoryPage(){const{data,error}=useStoryData();const[detail,setDetail]=useState<PopupDetail|null>(null),[recordId,setRecordId]=useState("");
 const chapter=useMemo(()=>buildJourney(data,"method")[0],[data]);const records=Object.values(data?.evidence||{}).filter(entry=>entry.public_display_allowed);const examples=records.filter((entry,index)=>records.findIndex(other=>other.file_name===entry.file_name)===index);const selected=examples.find(entry=>entry.evidence_id===recordId)||examples[0];
 const select=(item:JourneyItem)=>{if(!data)return;const index=Number(item.id.replace("method-","")),step=steps[index];if(!step)return;setDetail({title:`${index+1}. ${step.title}`,content:<MethodStageDetail key={item.id} data={data} index={index} title={step.title} body={step.body}/>})};
 return <ImageStoryFrame route="/methodology" world="method" background="/home-art/method-universe-reference.png" title={["How research becomes","an explorable world."]} eyebrow="FROM DOCUMENTS TO DISCOVERY" intro="Follow the research from original documents through extraction, evidence review and a connected model. Every view should retain a way back to its source." sections={sections} chapter={chapter} detail={detail} onClose={()=>setDetail(null)} onSelect={select} error={error}>{data&&<>
 <section id="method-parse" className="ih-story-card" data-home-section><div className="ih-card-heading"><span>01 / PARSE SOURCES</span><h2>Read the document.<br/>Preserve its context.</h2><p>Open the original report and turn through its pages. Keep its layout, tables and illustrations together.</p></div><div className="story-visual"><div className="story-art-large"><SubjectGlass name="report"/></div><label className="story-filter">Choose a source<select value={selected?.evidence_id||""} onChange={event=>setRecordId(event.target.value)}>{examples.map(entry=><option key={entry.evidence_id} value={entry.evidence_id}>{documentTitle(entry.file_name)}</option>)}</select></label><p>The original document remains separate from the study’s interpretation. Use the next section to inspect how a record was assessed.</p></div><div className="ih-inline-detail">{selected&&<ResearchDocumentReader fileName={selected.file_name} text=""/>}</div></section>
 <section id="method-audit" className="ih-story-card" data-home-section><div className="ih-card-heading"><span>02 / AUDIT EVIDENCE</span><h2>Check the claim.<br/>Keep its limits.</h2><p>Evidence strength and display eligibility are recorded assessments. They are not guarantees of every possible interpretation.</p></div><div className="story-visual"><div className="method-audit-illustration"><SubjectGlass name="claim"/><span>Source passage</span><b>→</b><SubjectGlass name="research"/><span>Reviewed interpretation</span></div><dl className="story-facts">{Object.entries(data.manifest.audit_summary?.audit_status_counts||{}).map(([status,count])=><div key={status}><dt>{({approved_context_only:"Company or industry context only",approved_display_safe:"Approved for public explanation",rejected_overclaim_risk:"Excluded: claim exceeds the evidence",rejected_research_only:"Excluded from public display"} as Record<string,string>)[status]||status.replaceAll("_"," ")}</dt><dd>{count} recorded assessments</dd></div>)}</dl><p>Counts describe the saved audit snapshot, not a job running now.</p></div><div className="ih-inline-detail">{selected&&<EvidenceRecordDetail key={selected.evidence_id} entry={selected}/>}</div></section>
 <section id="method-result" className="ih-story-card" data-home-section><div className="ih-card-heading"><span>03 / RESPONSIBLE AI RESULT</span><h2>An explorable model.<br/>Not an invented certainty.</h2><p>AI-assisted research becomes useful when readers can inspect the source, the interpretation and the limits separately.</p></div><div className="story-visual"><div className="story-art-large"><HomeSubjectArtwork cell={8}/></div><div className="method-result-counts"><div><strong>{data.graph.nodes.length}</strong><span>published subjects</span></div><div><strong>{data.graph.edges.length}</strong><span>recorded connections</span></div><div><strong>{records.length}</strong><span>public-display records</span></div></div></div><ResponsibleStudyStory/></section>
 </>}</ImageStoryFrame>;
}
