"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState, type CSSProperties, type ReactNode } from "react";
import { ArrowRight, ArrowUpRight, BookOpen, Boxes, Brain, Coins, Factory, FileSearch, Home, Leaf, Menu, Network, Pause, Play, Search, ShieldCheck, Truck, X } from "lucide-react";
import { HersheyOrb as Orb } from "./HersheyOrb";
import HomeCosmos from "./HomeCosmos";
import ReferenceUniverse from "./ApprovedHomeUniverse";
import SupplySubjectDetail from "./SupplySubjectDetail";
import SupplyExplorer from "./SupplyExplorer";
import SupplyConnectionDetail from "./SupplyConnectionDetail";
import EvidenceExplorer,{EvidenceRecordDetail} from "./EvidenceExplorer";
import HomeEvidenceStories from "./HomeEvidenceStories";
import "./approved-home.css";
import SiteFooter from "./SiteFooter";
import {useSceneSession} from "./SceneSession";
import { loadEnrichedArtifacts, type EnrichedArtifacts, type EvidencePreview, type GraphNode, type CostRecord } from "@/lib/hershey/enrichedArtifacts";
import "./home-experience.css";
import "./research-pages.css";
import SectionJourney,{buildJourney,type JourneyItem} from "./SectionJourney";
import JourneyPopup from "./JourneyPopup";

export type PageKind="supply"|"evidence"|"cost"|"sources"|"method";
const pageInfo={
 supply:{title:"From ingredients\nto the shelf.",desc:"Explore the connected product journey. Open a stage to inspect its evidence, relationships and benchmark costs.",world:1,art:1,eyebrow:"THE HERSHEY SUPPLY CHAIN"},
 evidence:{title:"Follow a claim\nto its source.",desc:"Search the approved evidence, explore its scope and read the source context behind each record.",world:2,art:3,eyebrow:"THE EVIDENCE LIBRARY"},
 cost:{title:"What goes\ninto the price?",desc:"Explore how ingredients, packaging, manufacturing, warehousing and freight contribute to the estimate for one bar.",world:3,art:4,eyebrow:"BENCHMARK COST INTELLIGENCE"},
 sources:{title:"Open the research\nbehind the model.",desc:"Explore the documents represented in the published evidence. Select a source to read its linked records and captured text.",world:4,art:5,eyebrow:"FROM SOURCE TO STORY"},
 method:{title:"How research becomes\nan explorable world.",desc:"Follow the original project’s document-to-evidence workflow, from raw research through parsing and auditing to this interactive website.",world:5,art:5,eyebrow:"THE AI PIPELINE"}
};
const navigation=[["Home","/",Home,"#83dfff"],["Supply Chain","/supply-chain",Network,"#9bcbff"],["Evidence","/evidence-brain",FileSearch,"#8cebbd"],["Cost Model","/cost-model",Coins,"#e9c77e"],["Sources","/sources",BookOpen,"#c4a2ff"],["How It Works","/methodology",Play,"#a7c5fb"]] as const;
const paths={supply:"/supply-chain",evidence:"/evidence-brain",cost:"/cost-model",sources:"/sources",method:"/methodology"};
export const textValue=(v?:string)=>v?.replaceAll("_"," ")||"Not recorded";
const cents=(v?:number|null)=>typeof v==="number"?v.toFixed(2)+"¢":"Not allocated";
function Art({index,className=""}:{index:number;className?:string}){return <div aria-hidden="true" className={"rp-art "+className} style={{"--art-x":(index%3)*50+"%","--art-y":Math.floor(index/3)*100+"%"} as CSSProperties}/>;}
function EvidenceDetail({entry}:{entry:EvidencePreview&{evidence_text?:string}}){return <EvidenceRecordDetail key={entry.evidence_id} entry={entry}/>;}
export default function ResearchPage({kind}:{kind:PageKind}){
 const [data,setData]=useState<EnrichedArtifacts|null>(null),[error,setError]=useState(""),[retry,setRetry]=useState(0),[menu,setMenu]=useState(false),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),[phase,setPhase]=useState(0);
 const [scenario,setScenario]=useState<"low"|"base"|"high">("base");
 const [detail,setDetail]=useState<{title:string;content:ReactNode;companion?:ReactNode}|null>(null);
 const sceneSession=useSceneSession();

 const info=pageInfo[kind];
 useEffect(()=>{let on=true;setError("");loadEnrichedArtifacts().then(d=>{if(on)setData(d)}).catch(e=>{if(on)setError(String(e))});return()=>{on=false}},[retry]);
 useEffect(()=>{const m=matchMedia("(prefers-reduced-motion: reduce)"),sync=()=>setReduced(m.matches);sync();m.addEventListener("change",sync);return()=>m.removeEventListener("change",sync)},[]);


 const open=(title:string,content:ReactNode,companion?:ReactNode)=>setDetail({title,content,companion});
 const chapters=useMemo(()=>buildJourney(data,kind,scenario),[data,kind,scenario]);
 const activeChapter=chapters[Math.min(chapters.length-1,Math.floor(phase))];
 const selectStory=(item:JourneyItem)=>{
  if(!data)return;
  if(kind==="supply"&&item.kind==="node"){const subject=data.graph.nodes.find(node=>node.id===item.id);if(subject)open(item.label,<SupplySubjectDetail key={item.id} data={data} node={subject}/>);return;}
  if(item.id.startsWith("LIBRARY:")){open("Explore the research story",<HomeEvidenceStories data={data}/>);return;}
  if(item.kind==="source"){const file=item.id.slice(4),entries=Object.values(data.evidence).filter(e=>e.public_display_allowed&&e.file_name===file);open(file.replaceAll("_"," "),<><p>This document supports {entries.length} published evidence records.</p>{entries.map(e=><details key={e.evidence_id}><summary>{textValue(e.primary_claim_role)} · {textValue(e.safe_scope)}</summary><EvidenceDetail entry={e}/></details>)}</>);return;}
  if(item.kind==="cost"){const r=data.costBreakdown.records?.find(r=>r.cost_bucket_id===item.id);if(r)open(r.label,<CostDetail r={r}/>);return;}
  if(item.kind==="evidence"){const e=data.evidence[item.id];if(e)open(e.file_name||"Evidence",<EvidenceDetail entry={e}/>);return;}
  if(item.kind==="ingredient"){const ingredient=data.ingredients.find(n=>n.ingredient_id===item.id);if(ingredient)open(item.label,<><p>{ingredient.origin_logic}</p><p>{textValue(ingredient.supplier_status)} · {textValue(ingredient.confidence_level)} confidence</p>{ingredient.approved_evidence_preview?.map(e=><details key={e.evidence_id}><summary>{e.file_name}</summary><EvidenceDetail entry={e}/></details>)}</>);return;}
  if(item.kind==="node"){const n=data.graph.nodes.find(n=>n.id===item.id);if(n)open(item.label,<><p>{n.description}</p><p>{textValue(n.relationshipStatus)} · {textValue(n.confidenceLevel)} confidence</p><h3>Related per-bar cost calculations</h3><CostRows records={costLinks(n,data.costBreakdown.records||[])} open={open}/>{n.cost?.base!=null&&<p>Recorded base: {cents(n.cost.base)}. Range: {cents(n.cost.low)}–{cents(n.cost.high)}.</p>}{!costLinks(n,data.costBreakdown.records||[]).length&&n.cost?.base==null&&<p>No separate cost allocation recorded for this node.</p>}{n.enrichedEvidencePreview?.map(e=><details key={e.evidence_id}><summary>{e.file_name}</summary><EvidenceDetail entry={e}/></details>)}</>);return;}
  open(item.label,<><p>{["The original project collects public company, product, ingredient, supplier, logistics and retail research.","Level 1 parsing extracts text, tables and image/OCR context into structured document records.","Evidence records preserve a source excerpt and its claim context.","The Level 2 audit classifies permitted scope, confidence and display eligibility.","Supplier, ingredient, cost and logistics packets connect qualified records.","Nodes and edges form the interactive product network.","The frontend reads the published display artifacts.","The reader can inspect evidence, costs and source context throughout the website."][Number(item.id.split("-")[1])]}</p>{item.id==="method-3"&&<dl className="rp-fields">{Object.entries(data.manifest.audit_summary?.audit_status_counts||{}).map(([k,v])=><div key={k}><dt>{textValue(k)}</dt><dd>{v}</dd></div>)}</dl>}<p>Recorded graph: {data.graph.nodes.length} nodes · {data.graph.edges.length} edges.</p></>);
 };
 return <div id="top" className={"hc-home rp-page rp-"+kind} data-motion-paused={paused||reduced}>
 {(kind==="supply"||kind==="evidence")?<ReferenceUniverse worldName={kind} artPath={"/home-art/"+kind+"-universe-reference.png"} progress={phase} paused={paused||reduced}/>:<HomeCosmos world={kind} chapter={phase} paused={paused||reduced}/>}
 <a href="#research-main" className="hc-skip">Skip to content</a>
 <header className="hc-header"><Link href="/" className="hc-brand"><strong>HERSHEY’S</strong><span>SUPPLY CHAIN AI<small>AN INDEPENDENT STUDY</small></span></Link><button className="hc-menu hc-pill" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}><Menu/></button><nav className={menu?"hc-nav is-open":"hc-nav"} aria-label="Main navigation">{navigation.map(([label,url,Icon,color])=><Link href={url} key={url} className="hc-pill" style={{"--tone":color} as CSSProperties} aria-current={url===paths[kind]?"page":undefined}><Orb color={color} size={33} decorative><Icon size={19}/></Orb>{label}</Link>)}</nav></header>
 <main id="research-main">{kind==="cost"&&<div className="rp-story-scenario" role="group" aria-label="Story cost scenario">{(["low","base","high"] as const).map(value=><button key={value} className="hc-pill" aria-pressed={scenario===value} onClick={()=>setScenario(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>}<SectionJourney luminous status={error?"error":data?"ready":"loading"} errorMessage={error} onRetry={()=>setRetry(retry+1)} chapters={chapters} onSelect={selectStory} onProgress={setPhase} paused={paused||reduced} detailOpen={!!detail} onEdge={edge=>kind==="supply"&&data?open(edge.materialFlow||"How these parts connect",<SupplyConnectionDetail key={edge.id} data={data} edge={edge} onSubject={node=>open(node.label||"Supply chain story",<SupplySubjectDetail key={node.id} data={data} node={node}/>)}/>):open(edge.materialFlow||"Connected context",<><p>{edge.tooltipText}</p><p>Relationship: {textValue(edge.relationshipStatus)}</p><p>Confidence: {textValue(edge.confidenceLevel)}</p></>)}/>
 <section id="page-explorer" className="rp-explorer">
 {error?<div role="alert" className="rp-panel"><h2>Research could not be loaded</h2><p>{error}</p><button className="hc-pill" onClick={()=>setRetry(retry+1)}>Retry</button></div>:!data?<p role="status">Loading the project’s published research…</p>:kind==="supply"?<SupplyExplorer data={data} open={open}/>:kind==="cost"?<Cost data={data} open={open} scenario={scenario} setScenario={setScenario}/>:kind==="method"?<Method data={data} open={open}/>:kind==="evidence"?<EvidenceExplorer data={data} open={open}/>:<Evidence data={data} open={open} sources={kind==="sources"}/>}
 </section></main><SiteFooter/>
 <button className="hc-motion hc-pill" onClick={()=>setPaused(!paused)} aria-pressed={paused||reduced} disabled={reduced}>{paused||reduced?<Play size={14}/>:<Pause size={14}/>} {reduced?"Reduced motion":paused?"Resume motion":"Pause motion"}</button>
 <JourneyPopup detail={detail} onClose={()=>setDetail(null)} items={chapters[sceneSession.session?.chapter??Math.min(chapters.length-1,Math.floor(phase))].items} art={activeChapter.art} onSelect={selectStory}/>
 </div>
}
type ExplorerProps={data:EnrichedArtifacts;open:(title:string,content:ReactNode)=>void};
function costLinks(n:GraphNode,records:CostRecord[]){
 const id=n.id||"", key=/SUGAR|ASR/.test(id)?"SUGAR":/COCOA|BARRY/.test(id)?"COCOA":/DAIRY|LAND_O/.test(id)?"MILK":/SOY/.test(id)?"SOY":/PGPR/.test(id)?"PGPR":/NATURAL/.test(id)?"NATURAL":/PACKAGING|WRAPPING/.test(id)?"PACKAGING":/WAREHOUSE|COST_STORAGE/.test(id)?"STORAGE":/CARRIER|COST_FREIGHT/.test(id)?"FREIGHT":/RETAIL/.test(id)?"RETAIL":/RESIDUAL/.test(id)?"RESIDUAL":/PROCESS|MANUFACTURING/.test(id)?"MANUFACTURING":"";
 return key?records.filter(r=>r.cost_bucket_id.includes(key)&&r.safe_display===true):[];
}
function CostRows({records,open}:{records:CostRecord[];open:ExplorerProps["open"]}){
 return <div className="rp-cost-rows">{records.map(r=><button key={r.cost_bucket_id} onClick={()=>open(r.label,<CostDetail r={r}/>)}><span>{r.label}</span><strong>{cents(r.base_cents_per_bar)}</strong><small>{cents(r.low_cents_per_bar)} – {cents(r.high_cents_per_bar)}</small><ArrowUpRight size={15}/></button>)}</div>
}
function CostDetail({r}:{r:CostRecord}){return <><p>{r.cost_logic||r.notes}</p><dl className="rp-fields"><div><dt>Low</dt><dd>{cents(r.low_cents_per_bar)}</dd></div><div><dt>Base</dt><dd>{cents(r.base_cents_per_bar)}</dd></div><div><dt>High</dt><dd>{cents(r.high_cents_per_bar)}</dd></div><div><dt>Confidence</dt><dd>{textValue(r.confidence_level)}</dd></div></dl><p>{r.notes}</p><p>Evidence type: {textValue(r.evidence_type)}</p><small>Cost record: {r.cost_bucket_id}</small></>}
function Supply({data,open}:ExplorerProps){
 const [mode,setMode]=useState("Ingredients"),[selected,setSelected]=useState<GraphNode>(data.graph.nodes[0]),[query,setQuery]=useState("");
 const records=(data.costBreakdown.records||[]).filter(r=>r.safe_display===true);
 const buckets=[{name:"Ingredients & partners",art:0,types:["ingredient_origin","supplier","processor"]},{name:"Manufacturing",art:1,types:["hershey_facility","manufacturing_process","visual_reference"]},{name:"To the shelf",art:2,types:["warehouse","distributor","retailer","consumer"]},...(mode==="Cost"?[{name:"Cost & retail",art:4,types:["cost_bucket"]}]:[])];
 const costs=costLinks(selected,records);
 const edges=data.graph.edges.filter(e=>e.source===selected.id||e.target===selected.id);
 const choose=(n:GraphNode)=>setSelected(n);
 return <><div className="rp-toolbar" role="group" aria-label="Supply chain view">{["Ingredients","Cost","Logistics","Confidence"].map(m=><button className="hc-pill" aria-pressed={m===mode} key={m} onClick={()=>setMode(m)}>{m}</button>)}<label className="rp-search"><Search size={18}/><input aria-label="Find a node" placeholder="Find an ingredient or stage" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="rp-network-layout"><div className="rp-streams">{buckets.filter((b,i)=>mode!=="Logistics"||i>0).map(b=><section className="rp-stream" key={b.name}><Art index={b.art}/><h2>{b.name}</h2>{data.graph.nodes.filter(n=>b.types.includes(n.type||"")&&(n.label||"").toLowerCase().includes(query.toLowerCase())).map(n=><button className="rp-node" aria-pressed={selected.id===n.id} onClick={()=>choose(n)} key={n.id}><Orb size={35} color={b.art===0?"#91eac0":b.art===1?"#efc181":"#8dd8ff"} decorative>{b.art===0?<Leaf size={17}/>:b.art===1?<Factory size={17}/>:<Truck size={17}/>}</Orb><span>{n.label}<small>{mode==="Confidence"?textValue(n.relationshipStatus):mode==="Cost"?costLinks(n,records).map(r=>cents(r.base_cents_per_bar)).join(" + ")||"See allocation":textValue(n.type)}</small></span></button>)}</section>)}</div>
 <aside className="rp-inspector"><p className="hc-eyebrow">SELECTED NODE</p><h2>{selected.label}</h2><p>{selected.hoverSummary||selected.description}</p><dl className="rp-fields"><div><dt>Relationship</dt><dd>{textValue(selected.relationshipStatus)}</dd></div><div><dt>Confidence</dt><dd>{textValue(selected.confidenceLevel)}</dd></div></dl><h3>Related benchmark costs</h3>{selected.type==="retailer"&&<p>The retail range is the combined model, not a quote from this individual store. Open the evidence for retailer-specific source context.</p>}{costs.length?<><CostRows records={costs} open={open}/><small>Related cost buckets per bar. Shared manufacturing allocations are not separate costs for each process stage.</small></>:selected.cost?.base!=null?<dl className="rp-fields"><div><dt>Base</dt><dd>{cents(selected.cost.base)}</dd></div><div><dt>Range</dt><dd>{cents(selected.cost.low)} – {cents(selected.cost.high)}</dd></div></dl>:<p>No separate cost allocation is recorded for this node. The complete cost model remains available below.</p>}
 <h3>Connections ({edges.length})</h3>{edges.map(e=><button className="rp-edge" key={e.id} onClick={()=>open(e.materialFlow||"Relationship",<><p>{e.tooltipText}</p><dl className="rp-fields"><div><dt>From</dt><dd>{data.graph.nodes.find(n=>n.id===e.source)?.label}</dd></div><div><dt>To</dt><dd>{data.graph.nodes.find(n=>n.id===e.target)?.label}</dd></div><div><dt>State</dt><dd>{textValue(e.relationshipStatus)}</dd></div><div><dt>Confidence</dt><dd>{textValue(e.confidenceLevel)}</dd></div></dl></>)}>{e.materialFlow}<ArrowUpRight size={14}/></button>)}
 <button className="hc-pill" onClick={()=>open(selected.label||"Node evidence",<>{(selected.enrichedEvidencePreview||[]).map(e=><details key={e.evidence_id}><summary>{e.file_name}</summary><EvidenceDetail entry={e}/></details>)}{!selected.enrichedEvidencePreview?.length&&<p>No evidence preview in this node record.</p>}</>)}>Open evidence <FileSearch size={17}/></button></aside></div>
 <section className="rp-section"><p className="hc-eyebrow">COST THROUGHOUT THE JOURNEY</p><h2>The existing per-bar calculations.</h2><CostRows records={records} open={open}/><p className="rp-note">{data.costBreakdown.residual_channel_pool?.safe_display_wording}</p></section></>
}
function Evidence({data,open,sources=false}:ExplorerProps&{sources?:boolean}){
 const [assetMode,setAssetMode]=useState(false);
 const [query,setQuery]=useState(""),[packet,setPacket]=useState(""),[confidence,setConfidence]=useState(""),[type,setType]=useState(""),[limit,setLimit]=useState(18);
 const all=Object.values(data.evidence).filter(e=>e.public_display_allowed===true);
 const entries=all.filter(e=>(!packet||e.packet===packet)&&(!confidence||e.confidence_level===confidence)&&(!type||e.source_type===type)&&((e.file_name||"")+" "+(e.audited_safe_website_wording||"")+" "+(e.evidence_text||"")).toLowerCase().includes(query.toLowerCase()));
 const docs=useMemo(()=>{const map=new Map<string,typeof entries>();entries.forEach(e=>{const key=e.file_name||"Unspecified source";map.set(key,[...(map.get(key)||[]),e])});return Array.from(map)},[entries]);
 const artLabels=["Ingredient illustration","Manufacturing illustration","Distribution and retail illustration","Evidence library illustration","Cost layers illustration","Research archive illustration"];
 const filters=[{label:"Topic",value:packet,set:setPacket,values:Array.from(new Set(all.map(e=>e.packet).filter(Boolean)))},{label:"Confidence",value:confidence,set:setConfidence,values:Array.from(new Set(all.map(e=>e.confidence_level).filter(Boolean)))},{label:"Source type",value:type,set:setType,values:Array.from(new Set(all.map(e=>e.source_type).filter(Boolean)))}];
 if(sources&&assetMode)return <><div className="rp-toolbar"><button className="hc-pill" onClick={()=>setAssetMode(false)}>Research documents</button><button className="hc-pill" aria-pressed="true">Visual assets</button></div><p className="rp-note">New artwork created for this interface. These illustrations provide visual context and do not establish evidence or supplier relationships.</p><div className="rp-results">{["Product illustration",...artLabels].map((label,i)=><button key={label} className="rp-source-card" onClick={()=>open(label,<><p>Generated interface artwork. Visual reference only.</p><div className={i===0?"rp-art rp-product-art":"rp-art"} style={{"--art-x":((i-1)%3)*50+"%","--art-y":Math.floor((i-1)/3)*100+"%"} as CSSProperties}/><p>Usage: {label.toLowerCase()} in the interactive story.</p><small>{i===0?"product.png":"scene-atlas.png"}</small></>)}><div className={i===0?"rp-art rp-product-art":"rp-art"} style={{"--art-x":((i-1)%3)*50+"%","--art-y":Math.floor((i-1)/3)*100+"%"} as CSSProperties}/><h3>{label}</h3><span>Visual reference <ArrowUpRight size={16}/></span></button>)}</div></>;
 return <>{sources&&<div className="rp-toolbar"><button className="hc-pill" aria-pressed="true">Research documents</button><button className="hc-pill" onClick={()=>setAssetMode(true)}>Visual assets</button></div>}<div className="rp-toolbar"><label className="rp-search"><Search size={20}/><input aria-label={sources?"Search sources":"Search evidence"} placeholder={sources?"Search documents or topics…":"Search claims or ingredients…"} value={query} onChange={e=>{setQuery(e.target.value);setLimit(18)}}/></label>{filters.map(f=><label className="rp-filter" key={f.label}>{f.label}<select value={f.value} onChange={e=>{f.set(e.target.value);setLimit(18)}}><option value="">All</option>{f.values.map(v=><option key={v} value={v}>{textValue(v)}</option>)}</select></label>)}</div><p className="rp-count" role="status">{sources?docs.length:entries.length} matching {sources?"documents":"evidence records"}</p>
 <div className="rp-results">{sources?docs.slice(0,limit).map(([file,items])=><button className="rp-source-card" key={file} onClick={()=>open(file,<><p>{items.length} published evidence records refer to this document.</p><p>The captured source excerpts are available below. The original local document is not published by this view.</p>{items.map(e=><details key={e.evidence_id}><summary>{textValue(e.primary_claim_role)} · {textValue(e.safe_scope)}</summary><EvidenceDetail entry={e}/></details>)}</>)}><Orb size={54} color="#c2a7ff" decorative><BookOpen size={24}/></Orb><h3>{file.replaceAll("_"," ")}</h3><p>{Array.from(new Set(items.map(e=>textValue(e.packet)))).join(" · ")}</p><span>{items.length} linked records <ArrowUpRight size={16}/></span></button>):entries.slice(0,limit).map(e=><button key={e.evidence_id} className="rp-result" onClick={()=>open(e.file_name||"Evidence",<EvidenceDetail entry={e}/>)}><Orb size={42} color="#8de8c1" decorative><FileSearch size={21}/></Orb><span><strong>{textValue(e.primary_claim_role)}</strong><p>{e.audited_safe_website_wording}</p><small>{e.file_name} · {textValue(e.safe_scope)}</small></span><span className="rp-badge">{textValue(e.confidence_level)}</span><ArrowUpRight size={18}/></button>)}</div>
 {!entries.length&&<div className="rp-panel"><h2>No matching records</h2><p>Try another phrase or clear the filters.</p><button className="hc-pill" onClick={()=>{setQuery("");setPacket("");setConfidence("");setType("")}}>Clear filters</button></div>}
 {(sources?docs.length:entries.length)>limit&&<button className="hc-pill rp-more" onClick={()=>setLimit(limit+18)}>Show more records <ArrowRight size={16}/></button>}
 <p className="rp-note">{sources?"This register is derived from the published approved evidence. Visual artwork used for this redesign is illustrative and is not included as research evidence.":"Confidence and scope are retained from the published evidence. Selecting a record reveals its captured source text and permitted interpretation."}</p></>
}
function Cost({data,open,scenario,setScenario}:ExplorerProps&{scenario:"low"|"base"|"high";setScenario:(value:"low"|"base"|"high")=>void}){
 const records=(data.costBreakdown.records||[]).filter(r=>r.safe_display===true),key=(scenario+"_cents_per_bar") as "base_cents_per_bar",physical=records.filter(r=>!["retail_price","residual_channel_pool"].includes(r.cost_type));
 const total=data.costBreakdown.physical_cost?.[key],retail=data.costBreakdown.retail_price?.[key],residual=data.costBreakdown.residual_channel_pool?.[key];
 return <><div className="rp-toolbar" role="group" aria-label="Cost scenario">{(["low","base","high"] as const).map(v=><button className="hc-pill" aria-pressed={scenario===v} onClick={()=>setScenario(v)} key={v}>{v[0].toUpperCase()+v.slice(1)} estimate</button>)}</div><div className="rp-cost-layout"><div className="rp-layers">{physical.map((r,i)=><button className="rp-cost-layer" key={r.cost_bucket_id} style={{"--layer-color":["#efd28c","#bca5fa","#82d5f6","#88e8c1"][i%4],"--layer-width":Math.max(5,(r[key]/Math.max(total||1,1))*100)+"%"} as CSSProperties} onClick={()=>open(r.label,<CostDetail r={r}/>)}><span>{r.label}</span><strong>{cents(r[key])}</strong><i/><small>{textValue(r.confidence_level)} confidence</small><ArrowUpRight size={16}/></button>)}</div><aside className="rp-price-comparison"><Art index={4}/><div><span>Estimated physical cost</span><strong>{cents(total)}</strong></div><div><span>Observed retail price</span><strong>{typeof retail==="number"?"$"+(retail/100).toFixed(2):"Not recorded"}</strong></div><div><span>Residual channel / commercial pool</span><strong>{cents(residual)}</strong><small>{data.costBreakdown.residual_channel_pool?.safe_display_wording}</small></div></aside></div><section className="rp-section"><h2>Inspect every assumption.</h2><p>The low and high residual values use the backend’s published bounds. They need not equal the difference between the same named retail and physical scenarios.</p><CostRows records={records} open={open}/></section></>
}
function Method({data,open}:ExplorerProps){
 const steps=[["Raw source vault","Public company, ingredient, supplier, logistics and retail research forms the source collection.",BookOpen],["Level 1 parser","Text, tables and OCR are extracted into structured document records.",FileSearch],["Evidence records","Claim records retain their source text and document attribution.",Boxes],["Level 2 auditor","Claims are classified by evidence strength, scope and display eligibility.",ShieldCheck],["Structured packets","Ingredient, supplier, cost and logistics records supply the product model.",Factory],["Node & edge builder","Entities and relationships form the navigable supply-chain graph.",Network],["Display artifacts","The published artifacts provide the data displayed by the frontend.",Brain],["Interactive website","Explore the model, then return to the evidence supporting each view.",Home]] as const;
 return <><div className="rp-pipeline">{steps.map(([title,body,Icon],i)=><button key={title} onClick={()=>open(title,<><p>{body}</p>{i===3?<dl className="rp-fields">{Object.entries(data.manifest.audit_summary?.audit_status_counts||{}).map(([key,value])=><div key={key}><dt>{textValue(key)}</dt><dd>{value}</dd></div>)}</dl>:i===5?<p>{data.graph.nodes.length} nodes and {data.graph.edges.length} edges in the published model.</p>:i===6?<p>Published artifact version: {data.manifest.manifest_version}. Snapshot date: {data.manifest.created_at}.</p>:<p>This stage is described by the original project plan. This page explains the workflow; it does not execute a new parsing or audit job.</p>}</>)}><Orb size={80} color={["#85dbff","#c4acff","#8dcaff","#87ecc2","#ecca82"][i%5]} decorative><Icon size={34}/></Orb><small>{String(i+1).padStart(2,"0")}</small><h3>{title}</h3><p>{body}</p><ArrowUpRight size={18}/></button>)}</div><section className="rp-section rp-method-end"><div><p className="hc-eyebrow">SCOPE & LIMITS</p><h2>The model stays connected<br/>to what the research supports.</h2><ul>{data.manifest.safe_display_rules?.map(rule=><li key={rule}>{rule}</li>)}</ul></div><div><Art index={5}/><Link href="/supply-chain" className="hc-pill hc-primary">Explore the supply chain again <ArrowRight size={20}/></Link><p>Independent academic project by Praveen Rathee.</p></div></section></>
}
