"use client";
import {documentIdentity} from "@/lib/hershey/documentIdentity";
import {useMemo,useState} from "react";
import ImageStoryFrame,{useStoryData} from "./ImageStoryFrame";
import {type JourneyChapter,type JourneyItem} from "./scene-model";
import {SubjectGlass,type StoryObjectName} from "./StoryObject";
import {EvidenceRecordDetail,documentTitle} from "./EvidenceExplorer";
import ResearchDocumentReader from "./ResearchDocumentReader";
import NodeResearch from "./NodeResearch";
import SubjectIllustration from "./SubjectIllustration";
import {scopeExplanation} from "./EvidenceExplorer";
import type {PopupDetail} from "./JourneyPopup";
import "./evidence-led-page.css";
import "./method-story.css";
const sections=[{id:"sources-overview",label:"Overview"},{id:"source-families",label:"Browse source families"},{id:"source-document",label:"Read a document"},{id:"source-artwork",label:"Visual references"}];
const families=[{id:"",name:"All research",object:"report"},{id:"ingredient",name:"Ingredients",object:"cocoa"},{id:"product",name:"Product",object:"packaging"},{id:"company",name:"Company context",object:"factory"},{id:"logistics",name:"Logistics",object:"truck"},{id:"retail",name:"Retail",object:"retail"}] as const;
const familyFor=(packet:string)=>/retail/.test(packet)?"retail":/logistic/.test(packet)?"logistics":/sku|packaging/.test(packet)?"product":/hershey_company/.test(packet)?"company":"ingredient";
const visuals:Array<{name:string;object:StoryObjectName;description:string}>=[{name:"Ingredient illustration",object:"cocoa",description:"A dimensional cocoa illustration used as a subject marker. It does not identify a farm or supplier."},{name:"Manufacturing illustration",object:"factory",description:"Illustrative factory artwork, not a photograph or a surveyed model of a Hershey facility."},{name:"Distribution illustration",object:"truck",description:"A generic transport illustration. It does not establish a carrier or a tracked route."},{name:"Research illustration",object:"report",description:"Decorative document artwork. Only the original report reader above contains the actual source pages."},{name:"Retail illustration",object:"retail",description:"A generic store illustration used alongside the real retailer names. It is not a photograph of a named store."}];
export default function SourcesStoryPage(){const{data,error}=useStoryData();const[query,setQuery]=useState(""),[family,setFamily]=useState(""),[chosen,setChosen]=useState(""),[page,setPage]=useState(0),[recordIndex,setRecordIndex]=useState(0),[visual,setVisual]=useState(0),[detail,setDetail]=useState<PopupDetail|null>(null);
 const docs=useMemo(()=>{const grouped=new Map<string,NonNullable<typeof data>["evidence"][string][]>();for(const entry of Object.values(data?.evidence||{})){if(!entry.public_display_allowed||!entry.file_name)continue;grouped.set(documentIdentity(entry.file_name),[...(grouped.get(documentIdentity(entry.file_name))||[]),entry]);}return Array.from(grouped,([identity,records])=>({name:records[0].file_name!,records,identity}));},[data]);
 const filtered=docs.filter(doc=>(!family||doc.records.some(record=>familyFor(record.packet||"")===family))&&[doc.name,...doc.records.map(record=>record.packet)].join(" ").toLowerCase().includes(query.toLowerCase()));
 const selected=docs.find(doc=>doc.name===chosen)||filtered[0]||docs[0],entry=selected?.records[Math.min(recordIndex,(selected?.records.length||1)-1)];
 const chapter=useMemo<JourneyChapter>(()=>{const core:JourneyItem={id:"SOURCE_ARCHIVE",label:"Source collection",kind:"method",color:"#cba8f4",core:true,position:{x:50,y:46}};const positions=[{x:20,y:9},{x:84,y:14},{x:15,y:69},{x:53,y:88},{x:88,y:71}];const subjects=families.slice(1).map((item,index):JourneyItem=>({id:"FAMILY:"+item.id,label:item.name,kind:"source",color:["#8edfc1","#bdadf3","#e3c08e","#9fdced","#c4aaf1"][index],artwork:item.object,position:positions[index],tag:docs.filter(doc=>doc.records.some(record=>familyFor(record.packet||"")===item.id)).length+" documents"}));return{label:"Source families",title:"Open the research",body:"Choose a source family to browse its documents.",art:5,pattern:"orbit",items:[core,...subjects],edges:subjects.map(item=>({id:"ARCHIVE:"+item.id,source:core.id,target:item.id,flowType:"collection_reference",relationshipStatus:"source_family",presentation:true,tooltipText:"Documents grouped by their recorded research subject, not a physical supply route."}))};},[docs]);
 const select=(item:JourneyItem)=>{if(!data)return;if(item.id.startsWith("FAMILY:")){const selectedFamily=item.id.slice(7);setFamily(selectedFamily);setPage(0);const matches=docs.filter(doc=>doc.records.some(record=>familyFor(record.packet||"")===selectedFamily));setDetail({title:item.label+" sources",content:<><NodeResearch key={item.id} data={data} evidenceIds={matches.flatMap(doc=>doc.records.map(record=>record.evidence_id!))}/></>});return;}if(item.id==="SOURCE_ARCHIVE")setDetail({title:"The source collection",content:<><NodeResearch key={item.id} data={data} evidenceIds={docs.flatMap(doc=>doc.records.map(record=>record.evidence_id!))}/></>});};
 return <ImageStoryFrame route="/sources" world="sources" background="/home-art/sources-universe-reference.png" title={["Open the research","behind the model."]} eyebrow="REAL SOURCES. A CONNECTED STORY." intro="Browse source families, open an original report, and distinguish the research from the illustrations used to explain it." sections={sections} chapter={chapter} detail={detail} onClose={()=>setDetail(null)} onSelect={select} error={error}>{data&&<>
 <section id="source-families" className="ih-story-card" data-home-section><div className="ih-card-heading"><span>01 / BROWSE BY SOURCE FAMILY</span><h2>Choose a topic.<br/>Find its documents.</h2><p>Each document appears once, with its related evidence grouped underneath.</p></div><div className="story-visual"><div className="story-choices">{families.map(item=><button key={item.id} aria-pressed={family===item.id} onClick={()=>{setFamily(item.id);setPage(0)}}><SubjectGlass name={item.object}/><span>{item.name}</span></button>)}</div><label className="story-filter">Search documents<input value={query} onChange={event=>{setQuery(event.target.value);setPage(0)}} placeholder="Document, company or subject…"/></label><p role="status">{filtered.length} unique documents</p></div><div className="ih-inline-detail"><div className="story-record-list">{filtered.slice(page*5,page*5+5).map(doc=><button className="research-story-card" key={doc.name} aria-pressed={selected?.name===doc.name} onClick={()=>{setChosen(doc.name);setRecordIndex(0)}}><span className="research-story-title"><SubjectIllustration name={families.find(f=>f.id===familyFor(doc.records[0]?.packet||""))?.object||"report"} size={48}/><strong>{documentTitle(doc.name)}</strong></span><p>{scopeExplanation(doc.records[0]?.safe_scope)}</p><small>{doc.records.length} linked records · Select this document for the reader below →</small></button>)}</div>{!filtered.length&&<p>No matching documents. Try another subject or search phrase.</p>}<div className="story-mini-actions"><button disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous</button><span>{filtered.length?page+1:0} / {Math.ceil(filtered.length/5)}</span><button disabled={(page+1)*5>=filtered.length} onClick={()=>setPage(value=>value+1)}>Next</button></div>{selected&&<a className="ih-inline-action" href="#source-document">Read {documentTitle(selected.name)} →</a>}</div></section>
 <section id="source-document" className="ih-story-card" data-home-section><div className="ih-card-heading"><span>02 / VIEW A SOURCE</span><h2>The document.<br/>The connected evidence.</h2><p>Read the original pages and inspect the study’s interpretation separately.</p></div><div className="story-visual"><h3>{documentTitle(selected?.name)}</h3>{entry&&<><EvidenceRecordDetail key={entry.evidence_id} entry={entry}/><div className="story-mini-actions"><button disabled={recordIndex<=0} onClick={()=>setRecordIndex(value=>value-1)}>Previous record</button><span>Record {recordIndex+1} / {selected?.records.length}</span><button disabled={recordIndex>=(selected?.records.length||1)-1} onClick={()=>setRecordIndex(value=>value+1)}>Next record</button></div></>}</div><div className="ih-inline-detail">{entry?<ResearchDocumentReader fileName={selected?.name} text={entry.evidence_text||entry.evidence_text_preview||"No captured text."}/>:<p>Select a source above.</p>}</div></section>
 <section id="source-artwork" className="ih-story-card" data-home-section><div className="ih-card-heading"><span>03 / VIEW A VISUAL REFERENCE</span><h2>Recognize the subject.<br/>Keep evidence distinct.</h2><p>Interface illustrations help tell the story; they are not research sources.</p></div><div className="story-visual"><div className="story-art-large"><SubjectGlass name={visuals[visual].object}/></div><div className="story-choices">{visuals.map((item,index)=><button key={item.name} aria-pressed={visual===index} onClick={()=>setVisual(index)}><SubjectIllustration name={item.object} size={42}/>{item.name.replace(" illustration","")}</button>)}</div></div><div className="ih-inline-detail"><h3>{visuals[visual].name}</h3><p>{visuals[visual].description}</p><dl className="story-facts"><div><dt>Asset type</dt><dd>Generated illustrative artwork</dd></div><div><dt>Use</dt><dd>Subject recognition in the interactive website</dd></div><div><dt>Evidence status</dt><dd>Visual context only. No supplier allocation or product certification is established by an image.</dd></div></dl></div></section>
 </>}</ImageStoryFrame>;
}
