"use client";
import {useEffect,useMemo,useRef,useState,type CSSProperties} from "react";
import {ArrowRight,ArrowUpRight,Pause,Play,Factory,Truck,Search,ShieldCheck,Package,FlaskConical} from "lucide-react";
import {loadEnrichedArtifacts,type EnrichedArtifacts,type GraphNode} from "@/lib/hershey/enrichedArtifacts";
import ProjectHeader from "./ProjectHeader";
import ReferenceUniverse from "./ApprovedHomeUniverse";
import LivingFlowScene from "./LivingFlowScene";
import {buildJourney,type JourneyItem,type JourneyEdge} from "./scene-model";
import {useSceneSession} from "./SceneSession";
import JourneyPopup,{type PopupDetail} from "./JourneyPopup";
import SupplySubjectDetail from "./SupplySubjectDetail";
import SupplyConnectionDetail from "./SupplyConnectionDetail";
import HomeStageFlow,{ProcessStepIcon} from "./HomeStageFlow";
import HomeSubjectArtwork from "./HomeSubjectArtwork";
import {HersheyOrb} from "./HersheyOrb";
import SiteFooter from "./SiteFooter";
import ConnectionSubjects from "./ConnectionSubjects";
import StoryObject from "./StoryObject";
import "./connection-subjects.css";
import "./home-experience.css";
import "./section-journey.css";
import "./approved-home.css";
import "./image-led-home.css";
import "./supply-led-page.css";
const sections=[{id:"supply-overview",label:"Overview"},{id:"supply-inputs",label:"Ingredient insights"},{id:"supply-making",label:"Manufacturing"},{id:"supply-connections",label:"Connections & evidence"}];
const inputs=[{id:"NODE_ORIGIN_COCOA",label:"Cocoa",cell:0,color:"#d8ba8b"},{id:"NODE_ORIGIN_SUGAR",label:"Sugar",cell:1,color:"#efcf93"},{id:"NODE_ORIGIN_DAIRY",label:"Dairy",cell:2,color:"#96dff3"},{id:"NODE_ING_SOY_LECITHIN",label:"Smaller inputs",cell:null,color:"#c7a4ef"},{id:"NODE_PACKAGING_STREAM",label:"Packaging",cell:null,color:"#b7d0f7"}] as const;
function MaterialPath({data,node}:{data:EnrichedArtifacts;node:GraphNode}){const first=data.graph.edges.find(e=>e.source===node.id),middle=data.graph.nodes.find(n=>n.id===first?.target),second=middle?.type==="supplier"?data.graph.edges.find(e=>e.source===middle.id):undefined,last=second?data.graph.nodes.find(n=>n.id===second.target):undefined;return <div className="sl-material-path" aria-label="Recorded ingredient path">{[node,middle,last].filter((n):n is GraphNode=>Boolean(n)).map((n,index)=><div key={n.id}><span>{n.type==="supplier"?"Company context":n.type==="manufacturing_process"?"Manufacturing stage":"Input"}</span><strong>{n.label}</strong>{index<([node,middle,last].filter(Boolean).length-1)&&<ArrowRight size={21}/>}</div>)}</div>}
export default function SupplyChainPage(){
 const[data,setData]=useState<EnrichedArtifacts|null>(null),[error,setError]=useState(""),[retry,setRetry]=useState(0),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),[active,setActive]=useState(0),[progress,setProgress]=useState(0),[visible,setVisible]=useState(true),[detail,setDetail]=useState<PopupDetail|null>(null),[selectedInput,setSelectedInput]=useState("NODE_ORIGIN_COCOA"),[query,setQuery]=useState(""),[process,setProcess]=useState("NODE_PROCESS_RECEIVING"),[edgeId,setEdgeId]=useState("EDGE_DOWNSTREAM_01");
 const hero=useRef<HTMLElement>(null),focus=useSceneSession();
 useEffect(()=>{let on=true;setError("");loadEnrichedArtifacts().then(d=>{if(on)setData(d)}).catch(e=>{if(on)setError(String(e))});return()=>{on=false}},[retry]);
 useEffect(()=>{const m=matchMedia("(prefers-reduced-motion: reduce)"),sync=()=>setReduced(m.matches);sync();m.addEventListener("change",sync);return()=>m.removeEventListener("change",sync)},[]);
 useEffect(()=>{const update=()=>{if(detail)return;let current=0,p=0;document.querySelectorAll<HTMLElement>(".supply-led-page [data-home-section]").forEach((el,i)=>{const r=el.getBoundingClientRect();if(r.top<=innerHeight*.35){current=i;p=i+Math.max(0,Math.min(.99,(innerHeight*.35-r.top)/r.height))}});setActive(current);setProgress(p);if(hero.current)setVisible(hero.current.getBoundingClientRect().bottom>0)};update();window.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);return()=>{window.removeEventListener("scroll",update);window.removeEventListener("resize",update)}},[data,detail]);
 const chapters=useMemo(()=>[buildJourney(data,"supply")[0]],[data]);
 const chosen=data?.graph.nodes.find(n=>n.id===selectedInput),processes=data?.graph.nodes.filter(n=>n.type==="manufacturing_process")||[];
 const links=data?.graph.edges.filter(e=>e.id&&e.source&&e.target)||[],edge=links.find(e=>e.id===edgeId);
 const inspectNode=(node:GraphNode)=>{if(data)setDetail({title:node.label||"Supply chain subject",content:<SupplySubjectDetail key={node.id} data={data} node={node}/>})};
 const inspect=(item:JourneyItem)=>{const node=data?.graph.nodes.find(n=>n.id===item.id);if(node)inspectNode(node)};
 const inspectEdge=(connection:JourneyEdge)=>{if(data)setDetail({title:connection.materialFlow||"How these parts connect",content:<SupplyConnectionDetail key={connection.id} data={data} edge={connection} onSubject={inspectNode}/>})};
 return <div id="top" className="hc-home image-led-home supply-led-page" data-active-section={active} data-motion-paused={paused||reduced}><ReferenceUniverse artPath="/home-art/supply-universe-reference.png" worldName="supply" progress={progress} paused={paused||reduced}/><a href="#supply-main" className="hc-skip">Skip to content</a><ProjectHeader current="/supply-chain"/>
 {!detail&&<nav className="ih-section-rail" aria-label="Supply Chain sections">{sections.map((s,i)=><a key={s.id} href={"#"+s.id} aria-current={active===i?"step":undefined}><span>{String(i).padStart(2,"0")}</span><b>{s.label}</b><i aria-hidden="true"/></a>)}</nav>}
 <main id="supply-main"><section ref={hero} className="ih-hero" data-home-section id="supply-overview"><div className="ih-hero-copy"><p className="ih-eyebrow">THE HERSHEY SUPPLY CHAIN</p><h1>From ingredients<span>to the shelf.</span></h1><p className="ih-intro">Follow the inputs, the making and the onward journey. Explore the evidence and existing cost estimates behind each part.</p><a className="ih-primary" href="#supply-inputs">Explore the connected story <ArrowRight size={21}/></a><p className="sl-hero-limit"><ShieldCheck size={17}/>Public research and modeled relationships—not a live shipment map.</p>{!data&&<div className="ih-load" role={error?"alert":"status"}>{error?<><p>Research could not load.</p><button onClick={()=>setRetry(retry+1)}>Try again</button></>:"Loading the published research…"}</div>}</div><div className="ih-scene" data-retained={Boolean(detail&&focus.session?.mode==="scene")} data-panel-side={focus.session?.side||"right"}><LivingFlowScene chapters={chapters} progress={0} connectionStyle="constellation" paused={paused||reduced} visible={visible} interactive={Boolean(data)} onSelect={inspect} onEdge={inspectEdge}/></div></section>
 <div className="ih-stories">{data&&<><section className="ih-story-card" data-home-section id="supply-inputs"><div className="ih-card-heading"><span>01 / INGREDIENT INSIGHTS</span><h2>Choose an input.<br/>Follow its connections.</h2><p>Ingredients, company context and costs answer different questions. Explore them together without treating a model as exact allocation.</p></div><div className="sl-input-scene"><div className="sl-subject-picks" role="group" aria-label="Ingredient streams">{inputs.map(item=><button key={item.id} aria-pressed={selectedInput===item.id} onClick={()=>{setSelectedInput(item.id);setQuery("")}}><HersheyOrb size={75} color={item.color} decorative>{item.cell!=null?<HomeSubjectArtwork cell={item.cell}/>:item.id.includes("PACKAGING")?<StoryObject name="packaging"/>:<StoryObject name="minor"/>}</HersheyOrb><span>{item.label}</span></button>)}</div><label className="sl-search"><Search size={20}/><input aria-label="Find a supply chain subject" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find an ingredient, company or stage…"/></label>{query&&<div className="sl-search-results">{data.graph.nodes.filter(n=>(n.label||"").toLowerCase().includes(query.toLowerCase())).slice(0,8).map(n=><button key={n.id} onClick={()=>{setSelectedInput(n.id!);setQuery("")}}>{n.label}<ArrowUpRight size={14}/></button>)}{!data.graph.nodes.some(n=>(n.label||"").toLowerCase().includes(query.toLowerCase()))&&<p>No subjects match that search.</p>}</div>}{chosen&&<MaterialPath data={data} node={chosen}/>}</div><div className="ih-inline-detail sl-detail">{chosen&&<SupplySubjectDetail key={chosen.id} data={data} node={chosen}/>}</div></section>
 <section className="ih-story-card" data-home-section id="supply-making"><div className="ih-card-heading"><span>02 / INSIDE THE PROCESS</span><h2>How the model<br/>makes the connection.</h2><p>Select a process step to see what comes before it and what follows. The stages are explanatory, not proprietary line records.</p></div><div className="sl-making-scene"><div className="sl-factory-art" aria-hidden="true"/><div className="sl-process-picks" role="group" aria-label="Manufacturing process stages">{processes.map(n=><button key={n.id} aria-pressed={process===n.id} onClick={()=>setProcess(n.id!)}><ProcessStepIcon nodeId={n.id!}/><span>{n.label}</span></button>)}</div></div><div className="ih-inline-detail sl-process-detail"><h3><Factory size={25}/>Manufacturing flow</h3><HomeStageFlow data={data} nodeId={process}/><div className="sl-cost-note"><strong>{data.calculationDetails.family_totals.manufacturing.base_cents_per_bar.toFixed(2)}¢</strong><span>shared manufacturing estimate per bar</span></div><p className="ih-fine">This is counted once in the cost model, not added for every process step.</p></div></section>
 <section className="ih-story-card" data-home-section id="supply-connections"><div className="ih-card-heading"><span>03 / FOLLOW A CONNECTION</span><h2>Open the relationship.<br/>Keep its limits visible.</h2><p>Inspect a recorded link, its cost context and related sources. Company context does not establish an exact route for this bar.</p></div><div className="sl-connection-scene"><ConnectionSubjects data={data} edge={edge}/><label>Choose a connection<select aria-label="Supply chain connection" value={edgeId} onChange={e=>setEdgeId(e.target.value)}>{links.map(e=><option key={e.id} value={e.id}>{data.graph.nodes.find(n=>n.id===e.source)?.label} → {data.graph.nodes.find(n=>n.id===e.target)?.label}</option>)}</select></label><div className="sl-route-caption"><span>The illustrations follow the two subjects you select.</span></div></div><div className="ih-inline-detail sl-detail">{edge&&<SupplyConnectionDetail key={edge.id} data={data} edge={edge as JourneyEdge} onSubject={inspectNode}/>}</div></section></>}</div></main><SiteFooter/><button className="ih-motion" disabled={reduced} aria-pressed={paused||reduced} onClick={()=>setPaused(!paused)}>{paused||reduced?<Play size={14}/>:<Pause size={14}/>} {reduced?"Reduced motion":paused?"Resume motion":"Pause motion"}</button><JourneyPopup detail={detail} onClose={()=>setDetail(null)}/></div>;
}
